### ISSUE TITLE
Decide what to do about unstable warnings

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/inotify-rs#11]
Currently, there are a lot of warnings about the use of unstable functionality in the code. If my understanding is correct, nothing unstable will be shipped with stable Rust versions following the release of Rust 1.0. I think it's very desirable for this library to work with stable versions, too.

The best decision for now is probably to wait. A lot of the unstable stuff might still become stable before 1.0. However, if there are still warnings shortly before the 1.0 release, we should probably attempt to replace the code in question with something else, if possible.

**Comment by dead10ck** [comment]
Yes, I agree, it's a better idea to leave them on for now. As I mentioned in a commit comment, most of them will probably go away as they get marked stable by the Rust team. And some of them are useful, e.g. I saw the warnings about the new slicing syntax. Like you said, if it gets close to 1.0 and there are still unstable warnings, they can be replaced with stable code.
