### ISSUE TITLE
Multiple `EventStream`s can take each other's events

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/inotify-rs#111]
It is possible to create multiple `EventStream`s from a single `Inotify` instance. Those streams will `read` from the same inotify file descriptor. Depending on the timing of the reads, one `EventStream` could end up with all the events, or both could end up with some of them. (Note: I haven't tested this. It's just my own reasoning).

It would be possible to guarantee there is only one `EventStream` per `Inotify` instance, by consuming or mutably borrowing `Inotify` when creating an `EventStream`. However, both those solutions would make `add_watch`/`rm_watch` inaccessible.

I have two ideas for how to solve this:
1. Duplicate `add_watch`/`rm_watch` on `EventStream`. That way, `EventStream` would effectively become a replacement for `Inotify` that uses a different method for reading events.
2. Split `Inotify` into two parts, one for managing watches, one for reading events.

I don't think solution 1 is flexible enough. `Stream` has a lot of methods that move the stream, which would make `add_watch`/`rm_watch` inaccessible again. This isn't really a solution, it's just kicking the problem one step down the line.

Solution 2 deserves a bit more elaboration:
- `Inotify` would become a struct with two fields, `watches` and `events`.
- `watches` would provide `add_watch`/`rm_watch` (which could be shortened to `add`/`remove`).
- `events` would provide the various `read_*` methods.
- `events` could be moved or borrowed when creating an `EventStream`, without affecting `watches`.

Right now I'm unsure what to do, although I like solution 2. I'm going to let this issue sit for a while before attempting an implementation. In the meantime, feedback is highly welcome.

**Comment by talklittle** [comment]
This issue is the same as #176 and #177

**Comment by hannobraun** [comment]
Thanks for letting me know, @talklittle! Closing in favor of those issues.
