### ISSUE TITLE
Async/Await syntax support

### ISSUE THREAD

**Issue by thedrow** [hannobraun/inotify-rs#121]
Futures 0.3 will support the Async/Await syntax.
One it reaches GA, Tokio will be next.
We should investigate what it will require of us to support the new syntax and prepare ourselves for it.

**Comment by thedrow** [comment]
Seems like 0.3 alpha 3 has a compatibility layer with futures 0.1 that includes Tokio compatibility.
Maybe we should try that first?

**Comment by hannobraun** [comment]
Thank you for opening this issue! 

I don't have the time to look into it right now (and likely won't have time for a while), but I agree that this is important. I'm happy to assist by reviewing reviewing pull requests or with general feedback.

Side note: There's [a problem](https://github.com/inotify-rs/inotify/issues/120) with the current stream-based API. Something to keep in mind when updating or redesigning the API.

**Comment by hannobraun** [comment]
We've had support for async/await for a while now. Closing.
