### ISSUE TITLE
Decide what to do if read returns 0

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/inotify-rs#15]
As I'm writing this, an error is returned, which might not be the best thing to do. See discussion in #14.

**Comment by blaenk** [comment]
I agree completely that a panic seems more appropriate for the reasons you stated. I only returned an error because that's what you were doing previously, so I figured you wanted to keep it that way. But yeah, the user has no control over that error appearing, so it's not exactly recoverable.

**Comment by hannobraun** [comment]
I think when I wrote that piece of code originally, I just looked at the documentation for `read` and translated the documented behaviour into the appropriate Rust idiom. I can't remember really thinking about how it behaved when used with inotify. So yeah, I think it was just wrong in the first place ;)

Thanks for looking into it!
