### ISSUE TITLE
Consider reverting #146 at some point

### ISSUE THREAD

**Issue by lnicola** [hannobraun/inotify-rs#151]
The compiler [dropped support](https://github.com/rust-lang/rust/issues/62516) for RHEL 5, so #146 can in principle be reverted when the MSRV gets bumped to 1.47.

**Comment by hannobraun** [comment]
Thanks for the note!

Do you think there's any pressure to revert that change? To me it seems like it doesn't make any difference in practical terms. But I'm happy to change it back, if it's causing problems for anyone.

**Comment by lnicola** [comment]
Nope, it's just cleaning up a workaround that's no longer needed. The two extra syscalls probably don't matter, but there's no point in having them. I filed this to keep track of it.

**Comment by hannobraun** [comment]
Makes sense, thanks again!
