### ISSUE TITLE
Cutting a release for #171 and #173

### ISSUE THREAD

**Issue by erickt** [hannobraun/inotify-rs#172]
Would it be possible to cut a release to fix the alignment issues in #171? I was just about to write a PR to fix the same thing, then I saw it was already fixed.

edit: also, I just saw some fcntl return results were not being checked, so I filed #173.

**Comment by hannobraun** [comment]
Thanks for opening this issue, @erickt! [Version 0.9.3 has been published](https://crates.io/crates/inotify).
