### ISSUE TITLE
Consider using cargo clippy in test workflows

### ISSUE THREAD

**Issue by i509VCB** [hannobraun/inotify-rs#181]
Clippy adds quite a few interesting lints that may be useful to have.

At the moment running clippy has 4 errors, mostly redundant field names in initialization. Clippy does also handle things such as warning you about unnecessary clones, redundant borrows on an already borrowed field, etc.

**Comment by hannobraun** [comment]
Thank you for opening this issue, @i509VCB. I'm all for that! It's just an issue of someone doing the work, i.e. adding Clippy to the CI build and fixing the existing warnings.

Pull requests welcome!
