### ISSUE TITLE
Using Inotify::read_events in async context

### ISSUE THREAD

**Issue by DBLouis** [hannobraun/inotify-rs#189]
Returning an empty iterator when `EGAIN/EWOULDBLOCK` is returned by `read` is not ideal in async context, for example in combination with tokio `AsyncFd`, because you need to detect "wouldblocks" but for that you have to consume the iterator. The iterator in neither `Clone` nor `ExactSizeIterator` which would help. I think that not handling this special case and letting the caller decide what to do with it is better.

**Comment by hannobraun** [comment]
Hi @DBLouis, thank you for opening this issue!

So you're saying that [this code](https://github.com/hannobraun/inotify-rs/blob/e6d464de8b030ac3b8a53ffd912fdd09d14c9047/src/inotify.rs#L376-L381) should be removed, in favor of just returning the error? That sounds sensible to me, and I'd be happy to merge a pull request that does that.

**Comment by DBLouis** [comment]
Thank you

**Comment by hannobraun** [comment]
Addressed by #190.
