### ISSUE TITLE
documentation for `Inotify::watches` is broken in 0.10.1

### ISSUE THREAD

**Issue by eric-seppanen** [hannobraun/inotify-rs#206]
The public crate docs [here](https://docs.rs/inotify/0.10.1/inotify/struct.Inotify.html#method.watches) have dead links to `Watches::add` and `Watches::remove`, that return a 404. I also notice that the return type `Watches` is not linked.

**Comment by hannobraun** [comment]
Thanks for reporting, @eric-seppanen! Not sure why this broke, but it hopefully shouldn't be too hard to fix.

**Comment by hannobraun** [comment]
Thank you, that makes sense. I've just confirmed that it works on `master`.

I've added releasing a new version to my list, and should hopefully get to it soon. Closing this issue, as it's already fixed in the repository.
