### ISSUE TITLE
Update dependency `bitflags` to v2?

### ISSUE THREAD

**Issue by LeoniePhiline** [hannobraun/inotify-rs#210]
`bitflags` v2 became available in March 2023: https://crates.io/crates/bitflags/versions 

Major changes: https://github.com/bitflags/bitflags/releases/tag/2.0.0

Maybe it is feasible to upgrade from v1 to v2?

**Comment by hannobraun** [comment]
I can't think of a reason to remove any of those implementations. I think it's probably best to keep all of them around. (I see that's what you've already done in your pull request :+1:)

**Comment by hannobraun** [comment]
Addressed in #211.
