### ISSUE TITLE
Recursive Directory Watching 

### ISSUE THREAD

**Issue by Chaqua** [hannobraun/inotify-rs#216]
Is there a way to watch a directory inside a directory inside a directory and so on.

e.g
- dir1
 |- dir2
  |- dir3

Because currently, I am only able to watch dir1, and if smth changes in dir2 or dir3 I dont get an event. Do I just have to add a watcher to each directory myself, or is there a function for that already I missed?

**Comment by hannobraun** [comment]
From the [inotify man page](https://www.man7.org/linux/man-pages/man7/inotify.7.html):

> Inotify monitoring of directories is not recursive: to monitor
> subdirectories under a directory, additional watches must be
> created.

You might want to consider using [Notify](https://crates.io/crates/notify), which provides a convenient API for watching directories recursively, and uses inotify under the hood on Linux.
