### ISSUE TITLE
Release with updated dependencies?

### ISSUE THREAD

**Issue by matthiasbeyer** [hannobraun/inotify-rs#217]
Hi,

can we have a release with updated dependencies? Especially the `bitflags` :wink:

**Comment by hannobraun** [comment]
Can do! I've put it on my list. No promises on when I'll get to it, but it _should_ happen within the next few weeks.

If you (or anybody else reading this) want to speed this up, you can help out by checking (and letting me know) whether https://github.com/hannobraun/inotify-rs/pull/211 is a breaking change. Once we know that, the release is a simple matter.

**Comment by hannobraun** [comment]
I've looked into it: It's a breaking change. I've merged https://github.com/hannobraun/inotify-rs/pull/218 to alleviate that a bit, but the overall change is still breaking, due to the [removal of the `bits` field](https://github.com/bitflags/bitflags/blob/main/CHANGELOG.md#%EF%B8%8F-bits-field).

**Comment by hannobraun** [comment]
Done. (https://github.com/hannobraun/inotify-rs/pull/220)
