### ISSUE TITLE
can't fetch new events without mutably borrowing the `INotify`

### ISSUE THREAD

**Issue by oli-obk** [hannobraun/inotify-rs#35]
see http://stackoverflow.com/questions/38078936/borrowing-reference-in-structure for a user having trouble with the API.

I suggest to split the method into two. One to fetch the events and one to read the events that were fetched.

**Comment by hannobraun** [comment]
Sounds sensible. I'd welcome a pull request to make that change. It might be a while before I can get to it myself.

**Comment by hannobraun** [comment]
I've recently started working on an API cleanup. I've decided the correct solution to this issue, for now, is for the user to allocate a `Vec`, and read events into that using `extend`. There's an example of that in the newly added documentation: https://github.com/hannobraun/inotify-rs/blob/78cf5d871cd24f29c70abb106ef06f8b4ed9baf8/src/wrapper.rs#L207

Please note that I'm not done with the current round of API improvements. I'm planning some changes that could remove this issue completely, but that may or may not work out.
