### ISSUE TITLE
Getting the full path to a modified file from an event

### ISSUE THREAD

**Issue by George3d6** [hannobraun/inotify-rs#68]
It seems to be that it's possible to watch multiple directories using the same inotify object.

However, I haven't found a way to extract the full path to a file/directory once an event occurs.

For example I could be watching two directories:

```
~/A
~/B
```

Both of them contain the file `test`

Now, assuming I modify the test in either A or B an get a notification I can get the name of the file as such:

`
let mut modified = event.name; //Will be the OsStr "test"
`

Which sadly enough doesn't seem to tell me what directory 'test' is a part of. 
Is it possible to get this information in any way without using separate inotify objects for each directory ? Or is the intended usage having a different inotify for each dir ?

**Comment by hannobraun** [comment]
Before I answer, first a clarification: inotify-rs is just a wrapper around Linux's inotify API, and it doesn't really do a whole lot on top of that. Therefore what you describe is not a behavior of inotify-rs, but of inotify itself.

I can't speak to the intended usage, but I think it's unnecessary to create one `Inotify` instance per directory. You should be able to distinguish the events using the `WatchDescriptor` returned by the `add_watch` method. `Event`'s field `wd` is a `WatchDescriptor` too, so you can use that to keep track of the various watches you added.

I'm going to close this issue, as I've answered the question. Feel free to post more comments though, if you have more questions, and feel free to reopen the issue if you believe there's something in inotify-rs that needs to be changed.

**Comment by arsalan86** [comment]
I'd like to add that there are known bugs in the version on crates.io (0.4.1), that have been fixed but not published. One of the bugs (see #60) is specific to `WatchDescriptor` and can potentially break your application. I suggest linking the dependency to the repository in your cargo.toml like so:

`inotify = { git = "https://github.com/hannobraun/inotify-rs.git", branch = "master" }`

The master branch has breaking changes, and some of the documentation needs to be updated to reflect that. Be aware that there are still bugs that need fixing.

Reading the [Inotify man pages](http://man7.org/linux/man-pages/man7/inotify.7.html) will be of great help. Inotify has it's quirks and it only helps to be aware of them when implementing the library.

**Comment by George3d6** [comment]
Thank you for the answers, I ended up going with the notify wrapper over this since it seems to implement all the functionality I need in a (hopefully reasonably fast) way.

I will however use the github rolling release style dependency with that one, since it probably uses 0.4.1 itself.

**Comment by hannobraun** [comment]
I think notify is the right choice for most uses cases. It's a bit behind with its depdency on inotify-rs though, it still depends on 0.3.0.
