### ISSUE TITLE
Issue with detecting Move to and Move from

### ISSUE THREAD

**Issue by George3d6** [hannobraun/inotify-rs#83]
Using the exact code in the README.md and adding the following:

>  else if event.mask.contains(event_mask::MOVED_FROM) {
>                 println!("Moved from {:?}", event.name);
>             } else if event.mask.contains(event_mask::MOVED_TO) {
>                 println!("Moved to {:?}", event.name);
>             } else {
>                 println!("Other event\n");
>             }

I am unable to detect the moving of a file (or at least some other event symbolized by the last else when I mv a file).

Using  inotifywait on the same directory yields the 'correct' events:

```
MOVED_FROM A
MOVED_TO B
```

When I run `mv A B`

**Comment by hannobraun** [comment]
Hi @George3d6, and sorry for the late reply.

Have you also modified the watch mask? Here's the relevant piece from the README:
```rust
inotify
    .add_watch(
        current_dir,
        watch_mask::MODIFY | watch_mask::CREATE | watch_mask::DELETE,
    )
    .expect("Failed to add inotify watch");
```
This tells inotify which events to watch for.

With something like this, it should work:
```rust
watch_mask::MODIFY | watch_mask::CREATE | watch_mask::DELETE | watch_mask::MOVE,
```

I'm closing this issue. Feel free to add more comments, if there's anything else you need help with.
